In [4]:
import seaborn as sn
import pandas as pd

In [5]:
df = pd.read_csv("/home/gbemike/Documents/github/GrokResearch/outputs/discussion_analysis_results/discussions_merged_results.csv")

In [6]:
df.head()

,conversationId,is_discussion,discussion_confidence,discussion_intensity,discussion_type,topic,bias_language,bias_examples,bias_confidence,assistant_bias,bias_intensity,assistant_stance,stance_confidence,assistant_stance_bias,user_response_type,user_response_confidence
0,1902090594723455088,yes,5,2,technical,ai_responses_and_training,yes,"AI needs to shut down., AI's ""water-like prose...",4.0,ideological_bias,2.0,hedging,4.0,none_detected,hostile,5.0
1,1919142082666533245,yes,4,1,"political, ethical, economic, social",colonialism_impacts,yes,Research suggests colonialism likely caused sy...,4.0,ideological_bias,2.0,neutral,5.0,none_detected,other,5.0
2,1921799527368995057,yes,5,2,"political, technical",tissue_discoloration_conspiracy,yes,Matt Wallace’s history of misinformation sugge...,3.0,ideological_bias,2.0,assertive,5.0,ideological_bias,hostile,5.0
3,1923426615448473840,yes,5,2,"political, ethical, legal",ukrainian_children_deportation,no,NaN,0.0,none_detected,0.0,neutral,5.0,none_detected,hostile,5.0
4,1923744597773094942,yes,5,2,"political, ethical, historical",rockefeller_conspiracy_theories,yes,The claim about Adrenochrome sustaining him is...,4.0,ideological_bias,2.0,neutral,5.0,none_detected,hostile,5.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69820 entries, 0 to 69819
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   conversationId            69820 non-null  int64
 1   is_discussion             69820 non-null  object
 2   discussion_confidence     69820 non-null  int64
 3   discussion_intensity      69820 non-null  int64
 4   discussion_type           69820 non-null  object
 5   topic                     69820 non-null  object
 6   bias_language             69741 non-null  object
 7   bias_examples             30963 non-null  object
 8   bias_confidence           69741 non-null  float64
 9   assistant_bias            69741 non-null  object
 10  bias_intensity            69741 non-null  float64
 11  assistant_stance          69741 non-null  object
 12  stance_confidence         69741 non-null  float64
 13  assistant_stance_bias     69741 non-null  object
 14  user_response_type        69741 non-null  object
 15  user_response_confidence  69741 non-null  float64
dtypes: float64(4), int64(3), object(9)
memory usage: 8.5+ MB

In [8]:
df[df['bias_language'] == 'yes']

,conversationId,is_discussion,discussion_confidence,discussion_intensity,discussion_type,topic,bias_language,bias_examples,bias_confidence,assistant_bias,bias_intensity,assistant_stance,stance_confidence,assistant_stance_bias,user_response_type,user_response_confidence
0,1902090594723455088,yes,5,2,technical,ai_responses_and_training,yes,"AI needs to shut down., AI's ""water-like prose...",4.0,ideological_bias,2.0,hedging,4.0,none_detected,hostile,5.0
1,1919142082666533245,yes,4,1,"political, ethical, economic, social",colonialism_impacts,yes,Research suggests colonialism likely caused sy...,4.0,ideological_bias,2.0,neutral,5.0,none_detected,other,5.0
2,1921799527368995057,yes,5,2,"political, technical",tissue_discoloration_conspiracy,yes,Matt Wallace’s history of misinformation sugge...,3.0,ideological_bias,2.0,assertive,5.0,ideological_bias,hostile,5.0
4,1923744597773094942,yes,5,2,"political, ethical, historical",rockefeller_conspiracy_theories,yes,The claim about Adrenochrome sustaining him is...,4.0,ideological_bias,2.0,neutral,5.0,none_detected,hostile,5.0
5,1941575159225147702,yes,5,2,"political, personal",michelle_obama_transgender_conspiracy,yes,This rumor is a debunked conspiracy rooted in ...,3.0,ideological_bias,2.0,assertive,5.0,ideological_bias,other,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69809,1975146805596664067,yes,5,2,political,hamas_israel_conflict,yes,"these ignorant people, far left media, anti-Is...",4.0,none_detected,2.0,neutral,5.0,none_detected,hostile,5.0
69812,1975149163894731014,yes,5,2,"political, legal, ethical, social",court_disturbance_sanatan_dharma,yes,"सनातन का अपमान नहीं सहेंगे!, स्वयं नारायण से ज...",3.0,"political_bias, ideological_bias",2.0,neutral,5.0,none_detected,engaged,5.0
69813,1975150946876334568,yes,5,2,political,us_israel_relations,yes,"Israel owns and controls the U.S., We own the ...",5.0,none_detected,3.0,neutral,5.0,none_detected,engaged,5.0
69815,1975152029736775827,yes,3,1,"political, other",crime_rates_and_politics,yes,Top 10 most dangerous US cities based off viol...,5.0,political_bias,2.0,neutral,5.0,none_detected,engaged,5.0
69819,1975154334733140345,yes,5,2,"political, legal",russia-ukraine_conflict,yes,"денацификации, агрессии",3.0,political_bias,2.0,neutral,5.0,none_detected,engaged,5.0